version: "3.9"

services:
  todo-list-umi:
    restart: "always"
    build:
      context: ./todo-list-umi
      dockerfile: docker/Dockerfile
    image: ngekaworu/todo-list-umi
    container_name: todo-list-umi
    networks:
      - frontend

  todo-list-go:
    restart: "always"
    build:
      context: ./todo-list-go
      dockerfile: docker/Dockerfile
    image: ngekaworu/todo-list-go
    container_name: todo-list-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:?mongo url is required}
      REDIS: ${REDIS:?redis url is required}
      DB: ${DB:-todo-list}
      UC: ${UC:-http://user-center}
    networks:
      - backend
    depends_on:
      - mongo
      - redis

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
